version: '3.8'

services:
  marvel-back:
    build: .
    container_name: marvel-back
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - marvel-db
    environment:
      - DB_HOST=marvel-db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432

  marvel-db:
    image: postgres:13
    container_name: marvel-db
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./marvel-db-data:/var/lib/postgresql/data
      - ./src/config/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  marvel-db-data:
